# Site settings
title: Shaun Walsh CV
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # The subpath of your site, e.g. /blog. Set this to an empty string for the root site.
url: "https://shaun-walsh.github.io" # The base hostname & protocol for your site, e.g. http://example.com

# Social links
twitter_username: jekyllrb
github_username: jekyll

# Build settings
# theme: jekyll-theme-minimal  # Keep this as default if you have a fallback theme.
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme  # Add the jekyll-remote-theme plugin for remote themes
  - jekyll-feed  # Add feed plugin for RSS feeds

# Exclude files and directories from being processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  
# Additional settings for Github Pages build environment
github:
  repository: shaun-walsh/shaun-walsh.github.io  # Change this to your repo name

# Theme configuration (optional settings)
remote_theme:
  source: pages-themes/midnight  # Name of the GitHub Pages theme
  version: v0.2.0  # Specific version to use (or omit for the latest version)

# Permalink settings
permalink: pretty  # Pretty URLs (e.g., /about/ instead of /about.html)

# Uncomment and customize the following if needed
# paginate: 10  # Number of posts per page
# paginate_path: "/page:num"  # Path for paginated pages
# markdown: kramdown  # Markdown processor
# collections:
#   my_collection:
#     output: true
#     permalink: /:path/
